spring.application.name=oidcapp-authorization-server

server.port=8080

logging.level.org.springframework.security=TRACE

spring.security.oauth2.authorizationserver.issuer=http://authserver.com:9080

