spring:
  application:
    name: api-server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: api_server
          client-secret: api_server_secret
          introspection-uri: http://authorization-server/oauth2/introspect

logging:
  level:
    org.springframework.security: TRACE