apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: oidcapp
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-server
  name: api-server
  namespace: oidcapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-server
    spec:
      containers:
      - image: mandarkul/oidcapp-api-server:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: oidcapp-api-server

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-server
  name: api-server
  namespace: oidcapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-server
  type: ClusterIP



